-- 내가 작성한 코드
SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK.PRICE*BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK, AUTHOR, BOOK_SALES
WHERE BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID 
AND BOOK.BOOK_ID = BOOK_SALES.BOOK_ID 
AND MONTH(SALES_DATE) = '1' AND YEAR(SALES_DATE) = '2022'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC
