-- 내가 작성한 코드
SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK.PRICE*BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK, AUTHOR, BOOK_SALES
WHERE BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID 
AND BOOK.BOOK_ID = BOOK_SALES.BOOK_ID 
AND MONTH(SALES_DATE) = '1' AND YEAR(SALES_DATE) = '2022'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC


-- MYSQL 다른 사람 코드
SELECT AB.AUTHOR_ID, C.AUTHOR_NAME, AB.CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM (SELECT *
       FROM BOOK_SALES AS A
       NATURAL JOIN BOOK AS B
       WHERE DATE_FORMAT(SALES_DATE, '%m') = '01') AS AB
INNER JOIN AUTHOR AS C
ON AB.AUTHOR_ID = C.AUTHOR_ID
GROUP BY AB.AUTHOR_ID, C.AUTHOR_NAME, AB.CATEGORY
ORDER BY AB.AUTHOR_ID ASC, AB.CATEGORY DESC;
