-- 내가 작성한 정답 코드
SELECT A.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM 
    (SELECT PRODUCT_NAME, PRICE, CATEGORY
     FROM FOOD_PRODUCT) AS A
     INNER JOIN 
     (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
      FROM FOOD_PRODUCT
      WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
      GROUP BY CATEGORY) AS B
      ON A.CATEGORY = B.CATEGORY 
      AND A.PRICE = B.MAX_PRICE
ORDER BY MAX_PRICE DESC

-- 다중 열 서브 쿼리 활용시 간단하게 작성가능한 코드
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
)
ORDER BY PRICE DESC;
