-- 내가 작성한 코드
-- DISTINCT 가 꼭 있어야 함.(상품을 구매한 회원수를 COUNT 하는 것이기에, 한 회원이 같은 달에 여러번 산거를 고려해야한다.)
SELECT YEAR(ONLINE_SALE.SALES_DATE) AS YEAR, 
MONTH(ONLINE_SALE.SALES_DATE) AS MONTH, 
USER_INFO.GENDER, COUNT(DISTINCT USER_INFO.USER_ID) AS USERS
FROM USER_INFO, ONLINE_SALE
WHERE USER_INFO.USER_ID	= ONLINE_SALE.USER_ID AND USER_INFO.GENDER IS NOT NULL
GROUP BY YEAR(ONLINE_SALE.SALES_DATE), MONTH(ONLINE_SALE.SALES_DATE), USER_INFO.GENDER
ORDER BY YEAR(ONLINE_SALE.SALES_DATE), MONTH(ONLINE_SALE.SALES_DATE), USER_INFO.GENDER
